---
training:
  per_device_batch_size: 32
  seq_len: 32
  seed: 0

optimizer:
  type: adam
  lr: 0.01
  epochs: 200
  wd: 0
  warmup: 0
  lr_decay: 0.01

rnn:
  use_rnn: true
  cell: lstm
  hidden_size: 128
  in_size: 300
  num_layers: 1
  bidirectional: false

transformer:
  use_transformer: false
  pt_model: bert-base-uncased
  hidden_size: 512

data:
  data_dir: ./data
  data_files: null
  drop_duplicates: true
  shuffle: true
  balance_data: [action]

embeddings:
  fasttext_file: null
  add_pos_embed: false

n_heads:
  out_sizes:
    action: 6
    object: null
    location: null
  use_bias: false

logging:
  eval_steps: 80
  save_file: lstm_action_model.tree
  run_name: lstm_action