---
training:
  per_device_batch_size: 32
  seq_len: 32
  seed: 0

optimizer:
  type: adamw
  lr: 0.0002
  epochs: 200
  wd: 0.01
  warmup: 0.1
  lr_decay: 0

rnn:
  use_rnn: false
  cell: lstm
  hidden_size: 128
  in_size: 300
  num_layers: 1
  bidirectional: false

transformer:
  use_transformer: true
  pt_model: bert-base-uncased

data:
  data_dir: ./data
  data_files: null
  drop_duplicates: true
  shuffle: true
  balance_data: null

embeddings:
  fasttext_file: null
  add_pos_embed: false

n_heads:
  out_sizes:
    action: 6
    object: 14
    location: 4
  use_bias: false

logging:
  eval_steps: 80
  save_file: bert_all_three_model.tree
  run_name: trfrmr_first

inference:
  run_infer: false
  run_id: jeevesh8/chat_cmds/runs
  test_file: ./test_data.csv